### ISSUE TITLE
Add YNAB Integration

### ISSUE THREAD

**Issue by nunonamorado** [fmfdias/tink-ynab#5]
- [x] Create YNAB Model
- [x] Add ynab-sdk-ruby gem
- [x] Create Service for transaction sincronization

**Comment by nunonamorado** [comment]
@fmfdias Achas que vale a pena guardar as transações que são geradas pela plataforma?

**Comment by fmfdias** [comment]
@nunonamorado acho que para já não vale a pena. A situação onde eu via isso dar jeito é para evitar entradas repetidas, mas acho que o YNAB deve dar conta disso (pelo menos com os qifs da)... com o avançar, se virmos que precisamos, então aí guardamos essa info. O que achas?

**Comment by nunonamorado** [comment]
@fmfdias Yup concordo. 👍
